name: Publish Preview Release
on:
  pull_request:

jobs:
  preview-release:
    if: github.repository == 'sveltejs/cli'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm

      # Disabled due to https://github.com/tj-actions/changed-files/issues/2463
      #      - name: Run changed-files
      #        id: changed-files
      #        uses: tj-actions/changed-files@v44
      #        with:
      #          separator: ' '
      #          dir_names: 'true'
      #          dir_names_max_depth: '2' # truncates the path to packages/package-name
      #          files: |
      #            packages/**

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build
#      - name: publish preview
#        if: ${{ steps.changed-files.outputs.all_changed_files_count > 0 }}
#        env:
#          CHANGED_DIRS: ${{ steps.changed-files.outputs.all_changed_files }}
#        # run: |
#        #   node scripts/get-deps-to-publish.js
#        run: pnpm dlx pkg-pr-new@0.0 publish --pnpm './packages/*'
